#!/bin/sh

mkdir -p /data/logs
DATE=`date +%Y-%m-%d:%H:%M:%S`

echo "###################"$DATE"###################" >> /data/logs/daily.0.log
#增加每日，龙虎榜数据。

nohup /usr/bin/python3 /data/stock/jobs/daily_job.py > /dev/null 2>/data/logs/daily.0.log &

#清除前3天数据。
#DATE_20=`date -d '-20 days' +%Y-%m-%d`
#MONTH_20=`date -d '-20 days' +%Y-%m`
#echo "rm -f /data/cache/hist_data_cache/$MONTH_20/$DATE_20"
#rm -f /data/cache/hist_data_cache/$MONTH_20/$DATE_20
